### ISSUE TITLE
Proposition: maxAge shoud be returned in ms, not in seconds.

### ISSUE THREAD

**Issue by Dryymoon** [nfriedly/set-cookie-parser#12]
max-age property shoud be returned in ms, not in seconds.
Express framework use for set cookie options maxAge in ms.

**Comment by nfriedly** [comment]
Hum... I understand why express did it (because JS timestamps are usually in ms), but the [spec](https://tools.ietf.org/html/rfc6265#section-5.2.2) (and the [cookie library](https://www.npmjs.com/package/cookie#maxage) that set-cookie-parser is based on) defines the field as being in seconds.

**Comment by nfriedly** [comment]
I did add a note to the readme to point out the difference in behavior.
