### ISSUE TITLE
Incompatibility with Fetch API

### ISSUE THREAD

**Issue by sshymko** [nfriedly/set-cookie-parser#13]
The cookie parser does not recognize response returned by the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API). That makes it nearly impossible to use the library in browser/Node.js/React Native environments.

The library assumes response to be a plain object with the `set-cookie` property. However, the [Fetch Response](https://developer.mozilla.org/en-US/docs/Web/API/Response) has a different interface:
```js
response.headers.get('Set-Cookie')
```
```js
response.headers.getAll('Set-Cookie')
```

**Comment by nfriedly** [comment]
From the readme:

> Accepts a single set-cookie header value, an array of set-cookie header values, or a response object that may have 0 or more set-cookie headers.

**Comment by nfriedly** [comment]
If you'd like to send a PR to make it also recognize fetch-style responses, that'd be welcome also ;)

**Comment by Ashoat** [comment]
It doesn't seem like passing the output from the fetch API works in all cases. It seems like "httponly" without a subsequent "=" will break the multi-cookie-parsing logic. Here's an example of what I'm seeing:

`console.log(response.headers.get('Set-Cookie'));
> "anonymous=39070%3A0d96462004e99ee7c13af7d8ebd1bdffc9abf6b2c95070429a1737fe37f43154; expires=Wed, 12-Apr-2017 19:58:28 GMT; Max-Age=2591999; path=/~ashoat/squadcal/; domain=localhost; httponly, user=39071%3A9d3f1baa12032ce4a2120c0c72e75297f3620defaad8c09905c4d03a92c87aad; expires=Wed, 12-Apr-2017 19:58:29 GMT; Max-Age=2592000; path=/~ashoat/squadcal/; domain=localhost; httponly, anonymous=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/~ashoat/squadcal/; domain=localhost; httponly"
console.log(response.headers.getAll('Set-Cookie'));
// note that whole cookie string (including multiple cookies) is returned as one header by getAll
> ["anonymous=39070%3A0d96462004e99ee7c13af7d8ebd1bdffc9abf6b2c95070429a1737fe37f43154; expires=Wed, 12-Apr-2017 19:58:28 GMT; Max-Age=2591999; path=/~ashoat/squadcal/; domain=localhost; httponly, user=39071%3A9d3f1baa12032ce4a2120c0c72e75297f3620defaad8c09905c4d03a92c87aad; expires=Wed, 12-Apr-2017 19:58:29 GMT; Max-Age=2592000; path=/~ashoat/squadcal/; domain=localhost; httponly, anonymous=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/~ashoat/squadcal/; domain=localhost; httponly"]
// same result occurs with headers.getAll
console.log(setCookie.parse(response.headers.get('Set-Cookie')));
> [ { domain: "localhost", expires: "Wed Dec 31 1969 19:00:01 GMT-0500 (EST)", httpOnly: true,
"httponly, anonymous": "deleted", "httponly, user": "39071%3A9d3f1baa12032ce4a2120c0c72e75297f3620defaad8c09905c4d03a92c87aad", maxAge: 0, name: "anonymous", path: "/~ashoat/squadcal/", value: "39070:0d96462004e99ee7c13af7d8ebd1bdffc9abf6b2c95070429a1737fe37f43154" } ]`

**Comment by nfriedly** [comment]
Oh, geze.  I didn't realize that `.get()` and .getAll()` join all of the headers into a single comma-separated string. That's going to be tricky to solve in the library because a header value could legitimately contain a string. If you're pretty sure that the headers you're going to be working with won't contain a string, then you can do something like this:

```js
setCookie.parse(response.headers.get('Set-Cookie').split(/, /g));
```

I think that will work for your use-case.

**Comment by nfriedly** [comment]
Also, how are you getting it to allow you access to the `Set-Cookie` headers? https://fetch.spec.whatwg.org/#forbidden-response-header-name says it's forbidden

**Comment by nfriedly** [comment]
I think I found a better solution - using a for/of loop, it's possible to access each header individually:

```js
var cookies = [];
for(var header of response.headers) {
  if (header[0] === 'set-cookie') {
    cookies.push(setCookie.parse(header[1]);
  }
}
console.log(cookies);
```

Also, how are you getting access to the `Set-Cookie` headers? The browser seems to block me from seeing them.

**Comment by Ashoat** [comment]
> Oh, geze. I didn't realize that .get() and .getAll() join all of the headers into a single comma-separated string.
[It looks like](http://stackoverflow.com/a/18967872/427010) according to RFC 6265, only a single Set-Cookie header can be set, and the cookies are thus joined into a single header by the server. I suspect that Node.js is handling the logic of splitting the single header into an array.

> `setCookie.parse(response.headers.get('Set-Cookie').split(/, /g));`
This won't work because the "expires" clause can contain a comma, as it does in the example I gave above.

> using a for/of loop, it's possible to access each header individually:
I don't follow the logic here - if there's only a single `Set-Cookie` header, won't this just lead to `setCookie.parse` getting passed the same long multi-cookie string as before?

> Also, how are you getting access to the Set-Cookie headers? The browser seems to block me from seeing them.
You guessed it - I am using React Native. I use httponly cookies with browsers to prevent against XSS attacks (I assume you're doing the same). React Native ignores httponly, likely because XSS attacks aren't a thing in React Native.

**Comment by nfriedly** [comment]
Try the for/of loop for me, if that doesn't work, then I'm not sure what to say :(

**Comment by sshymko** [comment]
Hey,

My understanding is that `response.headers.get()` should return a concatenated comma-separated string (not useful in case of `Set-Cookie` header). However, `response.headers.getAll()` should return an array of individual values. It is a bug [#12846](../../../facebook/react-native/issues/12846) of React Native that `getAll` "glues" values.

**Comment by sshymko** [comment]
For the record: loop `for..in` returns the same combined header value as `getAll()` in React Native.

**Comment by nfriedly** [comment]
Not `for...in`, `for...of`- they should have different behaviors.

**Comment by sshymko** [comment]
@nfriedly 
Thanks for the tip! Tested both `for...in` and `for...of` on the latest React Native v0.42. The first one results in 0 iterations, the latter one returns the combined header value.

**Comment by sshymko** [comment]
@nfriedly 
Thank you very much for reaching out to [whatwg/fetch](../../../whatwg/fetch/issues/506) for an advice.
The discussion there was eye-opening in terms of forbidding access to `Set-Cookie` headers.
That said, feel free to close the issue.
Thanks again.

**Comment by nfmshow** [comment]
I found this discussion really helpful

**Comment by ceciliazcx** [comment]
Is there any magic that everyone can get Set-Cookie field except me?

**Comment by nfriedly** [comment]
@ceciliazcx The short version is that access to the set-cookie header is not allowed in the fetch spec, but Node.js and React Native go ahead and allow it anyways. If you're not in one of those two environments, though, you shouldn't expect to have access to the header. (To be clear, "regular" React running in a browser will not have access to the set-cookie header from a fetch request.)

This library was intended for server side usage in Node.js, and then extended to work with React Native. You might be able to get it to work in other contacts, but it's not a guarantee.
