### ISSUE TITLE
Reverse mechanism?

### ISSUE THREAD

**Issue by Darker** [nfriedly/set-cookie-parser#15]
Is there also included a mechanism to convert the object with cookies into `Cookie:` HTTP header?

**Comment by nfriedly** [comment]
Not included, but it's based on, and largely compatible with https://www.npmjs.com/package/cookie 

You can see them used together here: https://github.com/nfriedly/node-unblocker/blob/master/lib/cookies.js
It's also mostly compatible with[Express's res.coomie()](http://expressjs.com/en/4x/api.html#res.cookie) method, with the exception that you must multiply the maxAge value by 1000.
