### ISSUE TITLE
Split cookies string

### ISSUE THREAD

**Issue by chrusart** [nfriedly/set-cookie-parser#18]
I made PR: https://github.com/joeferraro/react-native-cookies/pull/97
which parses multiple comma separated cookies in one string.

Discussion here as well:
https://github.com/nfriedly/set-cookie-parser/issues/13

Probably this functionality should go here instead?
This method returns array of cookie strings which this library can parse.

**Comment by nfriedly** [comment]
Nice work! I'd love to have that as part of this library as well, although I don't really like the idea of having two coppies of it floating around. If you and @joeferraro are both happy with the idea, you can send that code here in a PR, and then make the `react-native-cookies` depend on `set-cookie-parser`.

Or, if you guys prefer to go with the current route, then I might just tweak the readme here to show how to use the two libraries together.

**Comment by chrusart** [comment]
Actually I thought about it after I made PR in react-native-cookies and I honestly think it should go here.
BTW I've already made another commits and react-native-cookies will depend on set-cookie-parser to parse the single cookie string.

**Comment by chrusart** [comment]
PR coming soon!

**Comment by chrusart** [comment]
Done in https://github.com/nfriedly/set-cookie-parser/pull/19
