### ISSUE TITLE
Feature Request: Get cookie by name

### ISSUE THREAD

**Issue by kapilgarg1996** [nfriedly/set-cookie-parser#21]
Although its a very useful module but it lacks a basic feature to get a specific cookie by name. Whenever i have to get cookie , i will be doing a search on cookies array returned by this module. Can you add one utility function for the same task or i can submit a pull request regarding the same if you also feel that this feature should be added. Let me know. Thanks

**Comment by nfriedly** [comment]
Yeah, go ahead and send me a PR with the feature and a test or two.
