### ISSUE TITLE
Add sameSite option

### ISSUE THREAD

**Issue by maticzav** [nfriedly/set-cookie-parser#26]

**Comment by nfriedly** [comment]
It should be there already, is it not working?

https://github.com/nfriedly/set-cookie-parser/blob/c4a540c050805ff46c5efde37efffa71dca8514c/lib/set-cookie.js#L44-L45

**Comment by maticzav** [comment]
@nfriedly I was using the "TypeScript" version (i.e. the types provided), and they didn't include it. 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0bb210867d16170c4a08d9ce5d132817651a0f80/types/set-cookie-parser/index.d.ts#L23

**Comment by nfriedly** [comment]
Aah, want to send a PR to DefinitelyTyped then?

Also, the library has a fallback for unknown fields, where it just adds them to the object with the key lowercased - I'm not sure if TypeScript can represent that or not (?)

**Comment by maticzav** [comment]
Do you mind rewriting the library to TypeScript? I can help you out if you wish 🙂

**Comment by nfriedly** [comment]
Oh, yeah, I suppose that's an option. We're actually going through that process with one other library I wrote, but it's mostly than other people doing the work. I'm moving and have a 6-month-old, so I just don't have a whole lot of time to do much of the work myself.

But, if you're up for the challenge, then sure, I'm game. It's just probably going to end up being you doing most of the work :/

**Comment by maticzav** [comment]
@nfriedly happy to hear that! Let me see if I can squeeze a bit of extra work in the rewrite. I'll get back to you in the next couple of days, possibly with a PR.

**Comment by alanctkc** [comment]
Added a PR to the `@types` package for now!

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40422
