### ISSUE TITLE
export the parseString function

### ISSUE THREAD

**Issue by ajshetye** [nfriedly/set-cookie-parser#27]
Hi @nfriedly 
Thank you for the utility. I have a specific need for the utility. My node app sits between 2 apps and the app rewrites the set cookie on the response object by intercepting it. The parse function gives me the whole array so i have to rebuild the whole cookie object. The specific utility function `parseString` will make my life easy. Could you please export the function

**Comment by nfriedly** [comment]
I suppose I could export it 

Although, did you know that you can pass a single set-cookie header value into the parse function? It will still return an array, but the array will have only one value in it.

So instead of `parse(res)`, do something like `parse(myString)[0]`. Would that work for you?

**Comment by nfriedly** [comment]
I just pushed a v2.4.0 that exposes the parseString method for you in case my above suggestion doesn't work. It should get published to npm automatically in a minute or two here.

**Comment by ajshetye** [comment]
@nfriedly thanks for the commit. Also your above suggestion works the only caveat is I have to split the cookie before caling the function instead of parseString doing the work for me.
