### ISSUE TITLE
parseCookieString doesn't return map

### ISSUE THREAD

**Issue by oyeanuj** [nfriedly/set-cookie-parser#34]
Hi @nfriedly, thanks for this useful library! 

I was looking to use `parseString` method and I noticed that the `map` option doesn't really change the result. In both cases, the result is in the same form, unlike the Readme example. Here is the result:
```js
{
  name: 'authorization',
  value: 'somecrazyvalue'
}
```

Any idea what might be going on?

**Comment by nfriedly** [comment]
Hi @oyeanuj, thanks!

I think you want to use `parse` rather than `parseString`.

`parseString` doesn't accept the `map` option because it only returns a single cookie at a time. I should probably rename it...

**Comment by oyeanuj** [comment]
@nfriedly ah, got it. In that case, it would be cool if `parse` could accept the header or cookie string without necessarily needing the entire response object. 

For example, I'm using it with NextJS and they have the cookie string under `request.headers.cookie` which doesn't seem to work with `parse`.

**Comment by nfriedly** [comment]
Hum.. I wonder if you're confusing the `Cookie` header with the `Set-Cookie` header. The `Cookie` header goes on the `request` and is normally set by the browser when making a request to the server, but this library doesn't handle `Cookie` headers at all.

The `Set-Cookie` header is set by the server on the `response` and is (normally) parsed by the browser. This library allows your node.js server to parse `Set-Cookie` header(s) sent with responses from other servers. Those would be in `response.headers['set-cookie']`.

**Comment by oyeanuj** [comment]
@nfriedly: Ah, I didn't realize that this was for only for the `set-cookie` header even though I guess the name does suggest it. Any chance you'd be open to have this parse `Cookie` header as well since the logic is more or less the same?

**Comment by nfriedly** [comment]
Yea, I see what you're saying, but reading a `Cookie` header is a lot more common problem, and there are plenty of libraries out there that do it well, so I'm not sure it'd be all that beneficial to add it here.

Also, if you're using next.js, it parses `Cookie` headers for you automatically to `req.cookies` - see https://nextjs.org/docs/api-routes/api-middlewares

**Comment by nfriedly** [comment]
Since you're not the only person to get confused by this, I went ahead and added some code that checks for request objects with cookie headers and logs a warning to clarify the situation. Hopefully that will help save some time if someone else runs into this in the future :)
