### ISSUE TITLE
Returning Empty Object Error?

### ISSUE THREAD

**Issue by LittleWhiteLoti** [nfriedly/set-cookie-parser#36]
I was testing the code out to see if I could use this module because the popular cookie-parser package lacks good documentation. However, when I ran the snippet in the documentation all I got was an empty object. I know cookies exists because I set them using nodejs. 

Environment:
NodeJS v13.11.0
Express v4.17.1

The following is the code I ran.
```
const http = require("http");
const CookieParser = require("set-cookie-parser");

http.createServer((req, res) => 
{
    var cookies = CookieParser.parse(res, 
    {
        decodeValues: true,
        map: true
    });

    console.log(cookies);

}).listen(8080, "localhost");
```

When analyzing the request and response object, I found that the cookie it only exists in the request object under the request.headers.cookie. However, it does not display the other attributes, such as, path, domain, secure, httpOnly, sameSite, signed.

**Comment by nfriedly** [comment]
I think you're confusing the `Cookie` header with the `Set-Cookie` header. The cookie header is on the request, and there are lots of libraries that parse it, but not this one. The `Set-Cookie` header is on the response, in your case it would be set by the node.js server, not the browser. This library is useful if you want your node.js server to pretend it's a browser and contact another server, but you probably don't need to parse the `Set-Cookie` headed that your own node.js code set.

**Comment by nfriedly** [comment]
Since you're not the first person to get confused by this, I went ahead and added some code that checks for request objects with cookie headers and logs a warning to clarify the situation.  Hopefully that will help save some time if someone else runs into this in the future :)
