### ISSUE TITLE
Document how stringify set-cookie-parser object

### ISSUE THREAD

**Issue by gajus** [nfriedly/set-cookie-parser#40]
Suppose I parsed the `set-cookie` – How do I stringify it back after modifying it?

**Comment by nfriedly** [comment]
I use the `seralize` method from https://www.npmjs.com/package/cookie - you just have to extract the name and value, and then the other options can be passed in directly.

See https://github.com/nfriedly/node-unblocker/blob/9ca4899672f3265d436d0cf0b70050a5703b6d32/lib/cookies.js#L56-L70 (In that code, `setCookie` is this library `libCookie` is the cookie library I linked above.)

**Comment by nfriedly** [comment]
I went ahead and added an example to the readme: https://github.com/nfriedly/set-cookie-parser/blob/master/README.md#creating-a-new-modified-set-cookie-header

**Comment by gajus** [comment]
Thank you
