### ISSUE TITLE
Support for multiple cookies in one string

### ISSUE THREAD

**Issue by jerrysalonen** [nfriedly/set-cookie-parser#59]
When you use `fetch()` and the endpoint sets multiple `Set-Cookie` headers they all get serialized under the same key in the `Headers` object. It would be nice if this library supported passing multiple cookies in a single string for that use case. 

So for example if a request returns

```
Set-Cookie: foo=foo; Expires=Tue, 30 Jan 2024 14:04:53 GMT; SameSite=Lax
Set-Cookie: bar=bar; HttpOnly
```

Calling `res.headers.get('set-cookie')` just returns both of those cookies as one string, separated by a comma:

```js
{
  "Set-Cookie": "foo=foo; Expires=Tue, 30 Dec 2023 14:04:53 GMT; SameSite=Lax, Set-Cookie: bar=bar; HttpOnly"
}
```

I know there is a new `getSetCookie` function in the headers API but it does not have the [greatest support](https://developer.mozilla.org/en-US/docs/Web/API/Headers/getSetCookie#browser_compatibility) as of yet.

Maybe you could consume all the known cookie parameters until you reach and unknown one (the name of the next cookie) and then recursively continue parsing? I could have a go at a PR if you are open to that

**Comment by nfriedly** [comment]
Hi @jerrysalonen 

The library actually has a feature like what you're describing, it just requires an extra step to activate. See https://github.com/nfriedly/set-cookie-parser#usage-in-react-native-and-with-some-other-fetch-implementations

**Comment by jerrysalonen** [comment]
Ah, a classic case of RTFM. I must have skipped that section when I saw react native in the heading thinking it was not for my use case, thanks!

**Comment by nfriedly** [comment]
Just out of curiosity, what is your use case? Maybe I can make the title more relevant.

**Comment by Stevemoretz** [comment]
Worked for me as well, I don't have a special use-case, that's just how Laravel is sending headers to my Next.JS server side. (SSR) using `buildAxiosFetch`
