### ISSUE TITLE
Cookie is being parsed wrong...

### ISSUE THREAD

**Issue by vidz1979** [nfriedly/set-cookie-parser#66]
I have a fetch set-cookie header like this:

```
.AspNet.ExternalCookie=; path=/; expires=Thu, 01-Jan-1970 00:00:00 GMT; secure; HttpOnly, TagOneCookie=____a_big_cookie____; path=/; expires=Wed, 13-Nov-2024 15:28:55 GMT; secure
```

There are 2 cookies (.AspNet.ExternalCookie and TagOneCookie).

set-cookie-parser is not parsing it right:

```
{
  '.AspNet.ExternalCookie': {
    name: '.AspNet.ExternalCookie',
    value: '',
    path: '/',
    expires: 2024-11-13T15:28:55.000Z,
    secure: true,
    'httponly, tagonecookie': '____a_big_cookie____'
  }
}
```

**Comment by nfriedly** [comment]
Use `setCookie.splitCookiesString()` first. See https://github.com/nfriedly/set-cookie-parser?tab=readme-ov-file#usage-in-react-native-and-with-some-other-fetch-implementations for a full example.

**Comment by vidz1979** [comment]
Changed fetch to axios and now it's working!
